name: CI
on:
  push: {}
  pull_request: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["11"]
    steps:
    - uses: actions/checkout@master
    - name: Set Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Resolve
      run: swift package resolve
    - name: Generate Fixtures
      run: cd ./Tests/Fixtures && make
    - name: Build
      run: swift build
    - name: Test
      run: swift test
